# Generated by Django 4.0.5 on 2022-07-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
