# Generated by Django 4.0.5 on 2022-07-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_projects_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Ф.И.')),
                ('photo', models.FileField(help_text='Размер 4:4.5, формат .png', upload_to='C:\\Users\\andrey.pervushin\\PycharmProjects\\friendsEvents\\friendsevents\\media', verbose_name='Фото')),
                ('post', models.TextField(blank=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работники',
                'verbose_name_plural': 'Работники',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='groups',
            name='photo',
            field=models.FileField(help_text='Отображается в сетке главной страницы. Размер 3:2, формат .png', upload_to='C:\\Users\\andrey.pervushin\\PycharmProjects\\friendsEvents\\friendsevents\\media', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='slug',
            field=models.SlugField(help_text='Префикс в url ссылке на страницу.', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(help_text='Отображается в сетке. Размер 3:2, формат .png', upload_to='C:\\Users\\andrey.pervushin\\PycharmProjects\\friendsEvents\\friendsevents\\media'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='general_photo',
            field=models.FileField(help_text='Отображается в сетке. Размер 3:2, формат .png', upload_to='C:\\Users\\andrey.pervushin\\PycharmProjects\\friendsEvents\\friendsevents\\media', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='general.groups', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(help_text='Префикс в url ссылке на страницу.', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='video',
            field=models.FileField(blank=True, help_text='Видео 16:9 в .mp4. Не обязательно.', upload_to='C:\\Users\\andrey.pervushin\\PycharmProjects\\friendsEvents\\friendsevents\\media', verbose_name='Видео'),
        ),
    ]
