# Generated by Django 4.0.5 on 2022-07-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_employee_alter_groups_photo_alter_groups_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
    ]
